[project]
name = "yolov9py"
version = "0.1"
description = "YOLOv9 object detection model"
authors = [{name = "Rinor Ajeti", email = "r4ajeti@gmail.com"}]
license = {text = "MIT"}
requires-python = ">=3.6"
dependencies = [
    "numpy==1.26.4",
    "opencv-python-headless",
    "opencv-contrib-python",
    "scipy",
    "beautifulsoup4",
    "alive_progress==3.1.5",
    "requests>=2.23.0"
]

[project.optional-dependencies]
dev = [
    "Pillow>=7.1.2",
    "PyYAML>=5.3.1"
]

[project.urls]
Homepage = "https://github.com/R4Ajeti/yolov9"
